name: barbearianinja
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ninja.png
    - assets/logo.png
    - assets/imagem1.png
    - assets/imagem2.png
    - assets/imagem3.png
    - assets/imagem4.png
    - assets/imagem5.png
    - assets/imagem6.png
  fonts:
    - family: go3v2
      fonts:
        - asset: fonts/go3v2.ttf
    - family: zenzai
      fonts:
        - asset: fonts/zenzai.ttf
